name: TODO APP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          echo "Building the image"
          docker build -t todo-app .
  push:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: |
          echo "Logging in to Docker Hub"
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Tag Docker image
        run: |
          echo "Tagging the image"
          docker tag todo-app:latest ${{ secrets.DOCKER_USERNAME }}/todo-app:latest
      - name: Push Docker image to Docker Hub
        run: |
          echo "Pushing the image to Docker Hub"
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-app:latest
  deploy:
    runs-on: self-hosted
    needs: push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy container
        run: |
          echo "Deploying the container"
          docker run -d -p 8000:8000 mahe1kor/todo-app:latest
