name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          echo "Building the image"
          docker build -t todo-app .

      - name: Push to Docker Hub
        run: |
          echo "Pushing the image to Docker Hub"

      - name: Deploy container
        run: |
          echo "Deploying the container"
          # Add deployment commands here (e.g., kubectl, docker run, etc.)
